CREATE TABLE [DOSBOX] ( [ID] TEXT  NOT NULL, [VERSION] TEXT  NOT NULL );
CREATE UNIQUE INDEX [DOSBOX_INDEX] ON [DOSBOX]( [ID]  ASC );
CREATE TABLE [DOSBOXINFO] ( [ID] TEXT  NOT NULL, [TITLE] TEXT NULL, [YEAR] TEXT  NULL, [SW_HOUSE] TEXT  NULL, [LINK] TEXT  NULL, [COMP_PERSENT] TEXT NULL );
CREATE INDEX [DOSBOXINFO_INDEX] ON [DOSBOXINFO]( [ID]  ASC );
CREATE TABLE [GAME] ( [ID] TEXT  NOT NULL, [DB_ID] TEXT  NOT NULL, [NAME] TEXT NOT NULL, [EXEC] TEXT  NULL, [TEMPLATE] TEXT  NULL );
CREATE UNIQUE INDEX [GAME_INDEX] ON [GAME]( [ID]  ASC );
CREATE TABLE [GAMETEMPLATE] ( [ID] TEXT  NOT NULL, [TEMPLATE] TEXT NOT NULL );
CREATE INDEX [GAMETEMPLATE_INDEX] ON [GAMETEMPLATE]( [ID]  ASC );