<!DOCTYPE TS><TS>
<context>
    <name>ChangeLog</name>
    <message>
        <source>ChangeLog</source>
        <translation></translation>
    </message>
    <message>
        <source>DOSBox ChangeLog</source>
        <translation></translation>
    </message>
    <message>
        <source>DBoxFE ChangeLog </source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;/head&gt;&lt;body style=&quot; white-space: pre-wrap; font-family:Bitstream Vera Sans; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;&quot;&gt;&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;&quot;&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Ok</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>DBoxFE</name>
    <message>
        <source>DOSBox - Front End</source>
        <translation></translation>
    </message>
    <message>
        <source>Gameprofile</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Remove</source>
        <translation></translation>
    </message>
    <message>
        <source>Alt+R</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Save</source>
        <translation></translation>
    </message>
    <message>
        <source>Alt+S</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Create</source>
        <translation></translation>
    </message>
    <message>
        <source>Alt+C</source>
        <translation></translation>
    </message>
    <message>
        <source>St&amp;art</source>
        <translation></translation>
    </message>
    <message>
        <source>Alt+D</source>
        <translation></translation>
    </message>
    <message>
        <source>SDL, Render &amp;&amp; CPU</source>
        <translation></translation>
    </message>
    <message>
        <source>CPU</source>
        <translation></translation>
    </message>
    <message>
        <source>normal</source>
        <translation></translation>
    </message>
    <message>
        <source>full</source>
        <translation></translation>
    </message>
    <message>
        <source>dynamic</source>
        <translation></translation>
    </message>
    <message>
        <source>500</source>
        <translation></translation>
    </message>
    <message>
        <source>550</source>
        <translation></translation>
    </message>
    <message>
        <source>600</source>
        <translation></translation>
    </message>
    <message>
        <source>650</source>
        <translation></translation>
    </message>
    <message>
        <source>700</source>
        <translation></translation>
    </message>
    <message>
        <source>750</source>
        <translation></translation>
    </message>
    <message>
        <source>800</source>
        <translation></translation>
    </message>
    <message>
        <source>850</source>
        <translation></translation>
    </message>
    <message>
        <source>900</source>
        <translation></translation>
    </message>
    <message>
        <source>950</source>
        <translation></translation>
    </message>
    <message>
        <source>1000</source>
        <translation></translation>
    </message>
    <message>
        <source>1500</source>
        <translation></translation>
    </message>
    <message>
        <source>2000</source>
        <translation></translation>
    </message>
    <message>
        <source>2500</source>
        <translation></translation>
    </message>
    <message>
        <source>3000</source>
        <translation></translation>
    </message>
    <message>
        <source>3500</source>
        <translation></translation>
    </message>
    <message>
        <source>Core:</source>
        <translation></translation>
    </message>
    <message>
        <source>Cycles:</source>
        <translation></translation>
    </message>
    <message>
        <source>Cycledown:</source>
        <translation></translation>
    </message>
    <message>
        <source>Cycleup:</source>
        <translation></translation>
    </message>
    <message>
        <source>10</source>
        <translation></translation>
    </message>
    <message>
        <source>20</source>
        <translation></translation>
    </message>
    <message>
        <source>30</source>
        <translation></translation>
    </message>
    <message>
        <source>40</source>
        <translation></translation>
    </message>
    <message>
        <source>50</source>
        <translation></translation>
    </message>
    <message>
        <source>60</source>
        <translation></translation>
    </message>
    <message>
        <source>70</source>
        <translation></translation>
    </message>
    <message>
        <source>80</source>
        <translation></translation>
    </message>
    <message>
        <source>90</source>
        <translation></translation>
    </message>
    <message>
        <source>100</source>
        <translation></translation>
    </message>
    <message>
        <source>SDL</source>
        <translation></translation>
    </message>
    <message>
        <source>Hardwarescale:</source>
        <translation></translation>
    </message>
    <message>
        <source>Sensitivity:</source>
        <translation></translation>
    </message>
    <message>
        <source>Full wight/height:</source>
        <translation></translation>
    </message>
    <message>
        <source>640x480</source>
        <translation></translation>
    </message>
    <message>
        <source>800x600</source>
        <translation></translation>
    </message>
    <message>
        <source>1024x768</source>
        <translation></translation>
    </message>
    <message>
        <source>1280x1024</source>
        <translation></translation>
    </message>
    <message>
        <source>1600x1200</source>
        <translation></translation>
    </message>
    <message>
        <source>2480x1600</source>
        <translation></translation>
    </message>
    <message>
        <source>Autolock</source>
        <translation></translation>
    </message>
    <message>
        <source>Use Scancodes</source>
        <translation></translation>
    </message>
    <message>
        <source>Wait on Error</source>
        <translation></translation>
    </message>
    <message>
        <source>lowest,lowest</source>
        <translation></translation>
    </message>
    <message>
        <source>lowest,lower</source>
        <translation></translation>
    </message>
    <message>
        <source>lowest,normal</source>
        <translation></translation>
    </message>
    <message>
        <source>lowest,higher</source>
        <translation></translation>
    </message>
    <message>
        <source>lowest,highest</source>
        <translation></translation>
    </message>
    <message>
        <source>lower,lowest</source>
        <translation></translation>
    </message>
    <message>
        <source>lower,lower</source>
        <translation></translation>
    </message>
    <message>
        <source>lower,normal</source>
        <translation></translation>
    </message>
    <message>
        <source>lower,higher</source>
        <translation></translation>
    </message>
    <message>
        <source>lower,highest</source>
        <translation></translation>
    </message>
    <message>
        <source>normal,lowest</source>
        <translation></translation>
    </message>
    <message>
        <source>normal,lower</source>
        <translation></translation>
    </message>
    <message>
        <source>normal,normal</source>
        <translation></translation>
    </message>
    <message>
        <source>normal,higher</source>
        <translation></translation>
    </message>
    <message>
        <source>higher,lowest</source>
        <translation></translation>
    </message>
    <message>
        <source>higher,lower</source>
        <translation></translation>
    </message>
    <message>
        <source>higher,normal</source>
        <translation></translation>
    </message>
    <message>
        <source>higher,higher</source>
        <translation></translation>
    </message>
    <message>
        <source>higher,highest</source>
        <translation></translation>
    </message>
    <message>
        <source>highest,lowest</source>
        <translation></translation>
    </message>
    <message>
        <source>highest,lower</source>
        <translation></translation>
    </message>
    <message>
        <source>highest,normal</source>
        <translation></translation>
    </message>
    <message>
        <source>highest,higher</source>
        <translation></translation>
    </message>
    <message>
        <source>highest,highest</source>
        <translation></translation>
    </message>
    <message>
        <source>surface</source>
        <translation></translation>
    </message>
    <message>
        <source>overlay</source>
        <translation></translation>
    </message>
    <message>
        <source>opengl</source>
        <translation></translation>
    </message>
    <message>
        <source>openglnb</source>
        <translation></translation>
    </message>
    <message>
        <source>ddraw</source>
        <translation></translation>
    </message>
    <message>
        <source>Output:</source>
        <translation></translation>
    </message>
    <message>
        <source>Focus/Unfocus</source>
        <translation></translation>
    </message>
    <message>
        <source>Full screen</source>
        <translation></translation>
    </message>
    <message>
        <source>Full double</source>
        <translation></translation>
    </message>
    <message>
        <source>Full fixed</source>
        <translation></translation>
    </message>
    <message>
        <source>Render</source>
        <translation></translation>
    </message>
    <message>
        <source>Snapdir:</source>
        <translation></translation>
    </message>
    <message>
        <source>Frameskip:</source>
        <translation></translation>
    </message>
    <message>
        <source>Scaler:</source>
        <translation></translation>
    </message>
    <message>
        <source>Do aspect correction</source>
        <translation></translation>
    </message>
    <message>
        <source>Aspect</source>
        <translation></translation>
    </message>
    <message>
        <source>none</source>
        <translation></translation>
    </message>
    <message>
        <source>normal2x</source>
        <translation></translation>
    </message>
    <message>
        <source>normal3x</source>
        <translation></translation>
    </message>
    <message>
        <source>advmame2x</source>
        <translation></translation>
    </message>
    <message>
        <source>advmame3x</source>
        <translation></translation>
    </message>
    <message>
        <source>advinterp2x</source>
        <translation></translation>
    </message>
    <message>
        <source>interp2x</source>
        <translation></translation>
    </message>
    <message>
        <source>tv2x</source>
        <translation></translation>
    </message>
    <message>
        <source>tv3x</source>
        <translation></translation>
    </message>
    <message>
        <source>rgb2x</source>
        <translation></translation>
    </message>
    <message>
        <source>rgb3x</source>
        <translation></translation>
    </message>
    <message>
        <source>scan2x</source>
        <translation></translation>
    </message>
    <message>
        <source>scan3x</source>
        <translation></translation>
    </message>
    <message>
        <source>Sound</source>
        <translation></translation>
    </message>
    <message>
        <source>Mixer</source>
        <translation></translation>
    </message>
    <message>
        <source>Rate:</source>
        <translation></translation>
    </message>
    <message>
        <source>Block Size:</source>
        <translation></translation>
    </message>
    <message>
        <source>Wave dir:</source>
        <translation></translation>
    </message>
    <message>
        <source>11050</source>
        <translation></translation>
    </message>
    <message>
        <source>22050</source>
        <translation></translation>
    </message>
    <message>
        <source>44100</source>
        <translation></translation>
    </message>
    <message>
        <source>1024</source>
        <translation></translation>
    </message>
    <message>
        <source>2048</source>
        <translation></translation>
    </message>
    <message>
        <source>4096</source>
        <translation></translation>
    </message>
    <message>
        <source>waves</source>
        <translation></translation>
    </message>
    <message>
        <source>No sound</source>
        <translation></translation>
    </message>
    <message>
        <source>Soundbalster</source>
        <translation></translation>
    </message>
    <message>
        <source>Type:</source>
        <translation></translation>
    </message>
    <message>
        <source>IRQ:</source>
        <translation></translation>
    </message>
    <message>
        <source>OPL mode:</source>
        <translation></translation>
    </message>
    <message>
        <source>sb1</source>
        <translation></translation>
    </message>
    <message>
        <source>sb2</source>
        <translation></translation>
    </message>
    <message>
        <source>sbpro1</source>
        <translation></translation>
    </message>
    <message>
        <source>sbpro2</source>
        <translation></translation>
    </message>
    <message>
        <source>sb16</source>
        <translation></translation>
    </message>
    <message>
        <source>5</source>
        <translation></translation>
    </message>
    <message>
        <source>7</source>
        <translation></translation>
    </message>
    <message>
        <source>9</source>
        <translation></translation>
    </message>
    <message>
        <source>auto</source>
        <translation></translation>
    </message>
    <message>
        <source>cms</source>
        <translation></translation>
    </message>
    <message>
        <source>opl2</source>
        <translation></translation>
    </message>
    <message>
        <source>dualopl2</source>
        <translation></translation>
    </message>
    <message>
        <source>opl3</source>
        <translation></translation>
    </message>
    <message>
        <source>Base:</source>
        <translation></translation>
    </message>
    <message>
        <source>DMA:</source>
        <translation></translation>
    </message>
    <message>
        <source>HDMA:</source>
        <translation></translation>
    </message>
    <message>
        <source>OPL Rate:</source>
        <translation></translation>
    </message>
    <message>
        <source>220</source>
        <translation></translation>
    </message>
    <message>
        <source>240</source>
        <translation></translation>
    </message>
    <message>
        <source>1</source>
        <translation></translation>
    </message>
    <message>
        <source>3</source>
        <translation></translation>
    </message>
    <message>
        <source>GUS</source>
        <translation></translation>
    </message>
    <message>
        <source>Gus rate:</source>
        <translation></translation>
    </message>
    <message>
        <source>Gus Base:</source>
        <translation></translation>
    </message>
    <message>
        <source>IRQ&apos;s:</source>
        <translation></translation>
    </message>
    <message>
        <source>DMA&apos;s:</source>
        <translation></translation>
    </message>
    <message>
        <source>Ultra dir:</source>
        <translation></translation>
    </message>
    <message>
        <source>C:\ULTRASND</source>
        <translation></translation>
    </message>
    <message>
        <source>gus</source>
        <translation></translation>
    </message>
    <message>
        <source>Speaker</source>
        <translation></translation>
    </message>
    <message>
        <source>PC speaker</source>
        <translation></translation>
    </message>
    <message>
        <source>Tandy</source>
        <translation></translation>
    </message>
    <message>
        <source>Disney</source>
        <translation></translation>
    </message>
    <message>
        <source>Midi</source>
        <translation></translation>
    </message>
    <message>
        <source>Device:</source>
        <translation></translation>
    </message>
    <message>
        <source>Config:</source>
        <translation></translation>
    </message>
    <message>
        <source>default</source>
        <translation></translation>
    </message>
    <message>
        <source>alsa</source>
        <translation></translation>
    </message>
    <message>
        <source>oss</source>
        <translation></translation>
    </message>
    <message>
        <source>win32</source>
        <translation></translation>
    </message>
    <message>
        <source>coreaudio</source>
        <translation></translation>
    </message>
    <message>
        <source>MPU 401</source>
        <translation></translation>
    </message>
    <message>
        <source>Intelligent</source>
        <translation></translation>
    </message>
    <message>
        <source>Misc</source>
        <translation></translation>
    </message>
    <message>
        <source>Internet &amp;&amp; DOS</source>
        <translation></translation>
    </message>
    <message>
        <source>Mapper</source>
        <translation></translation>
    </message>
    <message>
        <source>Starmapper</source>
        <translation></translation>
    </message>
    <message>
        <source>Modem</source>
        <translation></translation>
    </message>
    <message>
        <source>COM Port:</source>
        <translation></translation>
    </message>
    <message>
        <source>Listen Port:</source>
        <translation></translation>
    </message>
    <message>
        <source>2</source>
        <translation></translation>
    </message>
    <message>
        <source>IPX</source>
        <translation></translation>
    </message>
    <message>
        <source>DOS</source>
        <translation></translation>
    </message>
    <message>
        <source>XMS</source>
        <translation></translation>
    </message>
    <message>
        <source>EMS</source>
        <translation></translation>
    </message>
    <message>
        <source>Direct serial</source>
        <translation></translation>
    </message>
    <message>
        <source>Real Port:</source>
        <translation></translation>
    </message>
    <message>
        <source>Default bps:</source>
        <translation></translation>
    </message>
    <message>
        <source>Parity:</source>
        <translation></translation>
    </message>
    <message>
        <source>Bytesize:</source>
        <translation></translation>
    </message>
    <message>
        <source>Stopbit:</source>
        <translation></translation>
    </message>
    <message>
        <source>COM1</source>
        <translation></translation>
    </message>
    <message>
        <source>COM2</source>
        <translation></translation>
    </message>
    <message>
        <source>1200</source>
        <translation></translation>
    </message>
    <message>
        <source>N</source>
        <translation></translation>
    </message>
    <message>
        <source>E</source>
        <translation></translation>
    </message>
    <message>
        <source>O</source>
        <translation></translation>
    </message>
    <message>
        <source>8</source>
        <translation></translation>
    </message>
    <message>
        <source>Other</source>
        <translation></translation>
    </message>
    <message>
        <source>Language:</source>
        <translation></translation>
    </message>
    <message>
        <source>Captures:</source>
        <translation></translation>
    </message>
    <message>
        <source>Open the language file for dosbox</source>
        <translation></translation>
    </message>
    <message>
        <source>wave</source>
        <translation></translation>
    </message>
    <message>
        <source>midi</source>
        <translation></translation>
    </message>
    <message>
        <source>capture</source>
        <translation></translation>
    </message>
    <message>
        <source>screenshot</source>
        <translation></translation>
    </message>
    <message>
        <source>Machine:</source>
        <translation></translation>
    </message>
    <message>
        <source>Memorysize:</source>
        <translation></translation>
    </message>
    <message>
        <source>hercules</source>
        <translation></translation>
    </message>
    <message>
        <source>cga</source>
        <translation></translation>
    </message>
    <message>
        <source>tandy</source>
        <translation></translation>
    </message>
    <message>
        <source>vga</source>
        <translation></translation>
    </message>
    <message>
        <source>16</source>
        <translation></translation>
    </message>
    <message>
        <source>32</source>
        <translation></translation>
    </message>
    <message>
        <source>64</source>
        <translation></translation>
    </message>
    <message>
        <source>128</source>
        <translation></translation>
    </message>
    <message>
        <source>256</source>
        <translation></translation>
    </message>
    <message>
        <source>512</source>
        <translation></translation>
    </message>
    <message>
        <source>Autoexec</source>
        <translation></translation>
    </message>
    <message>
        <source>Windows 2000/XP and Linux CD/DVD ROM</source>
        <translation></translation>
    </message>
    <message>
        <source>Windows 98 CD/DVD ROM</source>
        <translation></translation>
    </message>
    <message>
        <source>Use directory as CD/DVD ROM</source>
        <translation></translation>
    </message>
    <message>
        <source>Use directory as floppy drive</source>
        <translation></translation>
    </message>
    <message>
        <source>Use label for CD/DVD ROM</source>
        <translation></translation>
    </message>
    <message>
        <source>Directory for dosbox:</source>
        <translation></translation>
    </message>
    <message>
        <source>A</source>
        <translation></translation>
    </message>
    <message>
        <source>B</source>
        <translation></translation>
    </message>
    <message>
        <source>C</source>
        <translation></translation>
    </message>
    <message>
        <source>D</source>
        <translation></translation>
    </message>
    <message>
        <source>F</source>
        <translation></translation>
    </message>
    <message>
        <source>G</source>
        <translation></translation>
    </message>
    <message>
        <source>H</source>
        <translation></translation>
    </message>
    <message>
        <source>I</source>
        <translation></translation>
    </message>
    <message>
        <source>J</source>
        <translation></translation>
    </message>
    <message>
        <source>K</source>
        <translation></translation>
    </message>
    <message>
        <source>L</source>
        <translation></translation>
    </message>
    <message>
        <source>M</source>
        <translation></translation>
    </message>
    <message>
        <source>P</source>
        <translation></translation>
    </message>
    <message>
        <source>Q</source>
        <translation></translation>
    </message>
    <message>
        <source>R</source>
        <translation></translation>
    </message>
    <message>
        <source>S</source>
        <translation></translation>
    </message>
    <message>
        <source>T</source>
        <translation></translation>
    </message>
    <message>
        <source>U</source>
        <translation></translation>
    </message>
    <message>
        <source>V</source>
        <translation></translation>
    </message>
    <message>
        <source>W</source>
        <translation></translation>
    </message>
    <message>
        <source>X</source>
        <translation></translation>
    </message>
    <message>
        <source>Y</source>
        <translation></translation>
    </message>
    <message>
        <source>Z</source>
        <translation></translation>
    </message>
    <message>
        <source>Add</source>
        <translation></translation>
    </message>
    <message>
        <source>Remove</source>
        <translation></translation>
    </message>
    <message>
        <source>Update</source>
        <translation></translation>
    </message>
    <message>
        <source>Label for device:</source>
        <translation></translation>
    </message>
    <message>
        <source>DBoxFE Config</source>
        <translation></translation>
    </message>
    <message>
        <source>Log</source>
        <translation></translation>
    </message>
    <message>
        <source>Language</source>
        <translation></translation>
    </message>
    <message>
        <source>English</source>
        <translation></translation>
    </message>
    <message>
        <source>German</source>
        <translation></translation>
    </message>
    <message>
        <source>Executable/DOSBox binary</source>
        <translation></translation>
    </message>
    <message>
        <source>DOSBox binary:</source>
        <translation></translation>
    </message>
    <message>
        <source>About</source>
        <translation></translation>
    </message>
    <message>
        <source>Author</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;/head&gt;&lt;body style=&quot; white-space: pre-wrap; font-family:Bitstream Vera Sans; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;&quot;&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; font-size:8pt;&quot;&gt;&lt;span style=&quot; font-size:12pt; font-weight:600;&quot;&gt;Developer:&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;/head&gt;&lt;body style=&quot; white-space: pre-wrap; font-family:Bitstream Vera Sans; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;&quot;&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; font-size:8pt;&quot;&gt;&lt;span style=&quot; font-size:12pt; font-weight:600;&quot;&gt;First Nick:<byte value="x9"/>&lt;/span&gt;&lt;span style=&quot; font-size:12pt;&quot;&gt;ChMaster &amp;amp; LFreak &amp;amp; ChMaster|LFreak&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Real Name:&lt;/span&gt;Alexander Saal&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg;&quot;&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;E-Mail:<byte value="x9"/>&lt;/span&gt;&lt;span style=&quot; color:#0000ff;&quot;&gt;alex.saal@gmx.de&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;/head&gt;&lt;body style=&quot; white-space: pre-wrap; font-family:Bitstream Vera Sans; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;&quot;&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; font-size:8pt;&quot;&gt;&lt;span style=&quot; font-size:12pt; font-weight:600;&quot;&gt;Designer:&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;/head&gt;&lt;body style=&quot; white-space: pre-wrap; font-family:Bitstream Vera Sans; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;&quot;&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; font-size:8pt;&quot;&gt;&lt;span style=&quot; font-size:12pt; font-weight:600;&quot;&gt;(C)opyright:&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>Alexander Saal</source>
        <translation></translation>
    </message>
    <message encoding="UTF-8">
        <source>© &apos;2004, 2005, 2006</source>
        <translation></translation>
    </message>
    <message>
        <source>License</source>
        <translation></translation>
    </message>
    <message>
        <source>Thanks</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head&gt;&lt;meta name=&quot;qrichtext&quot; content=&quot;1&quot; /&gt;&lt;/head&gt;&lt;body style=&quot; white-space: pre-wrap; font-family:Bitstream Vera Sans; font-size:12pt; font-weight:400; font-style:normal; text-decoration:none;&quot;&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; font-size:9pt;&quot;&gt;&lt;span style=&quot; font-size:12pt; font-weight:600;&quot;&gt;KConfig: &lt;/span&gt;&lt;span style=&quot; font-size:12pt;&quot;&gt;Michael Goettsche&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg;&quot;&gt;&lt;span style=&quot; font-size:10pt; color:#000000;&quot;&gt;(KConfig code removed - QSettings is now used)&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg;&quot;&gt;&lt;span style=&quot; color:#0000ff;&quot;&gt;michi.goettsche@gmx.de&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#0000ff;&quot;&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#0000ff;&quot;&gt;&lt;span style=&quot; font-weight:600; color:#000000;&quot;&gt;Gameprofile: &lt;/span&gt;&lt;span style=&quot; color:#000000;&quot;&gt;anda_skoa&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#000000;&quot;&gt;&lt;span style=&quot; color:#0000ff;&quot;&gt;http://www.mrunix.de/forums/member.php?find=lastposter&amp;amp;t=42863&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#0000ff;&quot;&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#0000ff;&quot;&gt;&lt;span style=&quot; font-weight:600; color:#000000;&quot;&gt;DOSBox: &lt;/span&gt;&lt;span style=&quot; color:#000000;&quot;&gt;The DOSBox Crew&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#000000;&quot;&gt;&lt;span style=&quot; font-size:11pt; color:#0000ff;&quot;&gt;http&lt;/span&gt;&lt;span style=&quot; color:#0000ff;&quot;&gt;://dosbox.sourceforgef.net&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot;-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#0000ff;&quot;&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; font-weight:600; color:#000000;&quot;&gt;XMLPreferences:&lt;span style=&quot; font-weight:400; color:#0000ff;&quot;&gt; &lt;/span&gt;&lt;span style=&quot; font-weight:400;&quot;&gt;Angius Fabrizio (OSDaB)&lt;/span&gt;&lt;/p&gt;&lt;p style=&quot; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:MS Shell Dlg; color:#000000;&quot;&gt;&lt;span style=&quot; color:#0000ff;&quot;&gt;http://osdab.sourceforge.net&lt;/span&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>Would you realy quit?</source>
        <translation></translation>
    </message>
    <message>
        <source>Yes</source>
        <translation></translation>
    </message>
    <message>
        <source>No</source>
        <translation></translation>
    </message>
    <message>
        <source>Please select profile.</source>
        <translation></translation>
    </message>
    <message>
        <source>Configuration file not found!

&apos;</source>
        <translation></translation>
    </message>
    <message>
        <source>&apos;</source>
        <translation></translation>
    </message>
    <message>
        <source>Can not start dosbox, no dosbox binary was selected.
Please choose dosbox binary.</source>
        <translation></translation>
    </message>
    <message>
        <source>Please select profile to delet it!</source>
        <translation></translation>
    </message>
    <message>
        <source>Please select profile for remove from list!</source>
        <translation></translation>
    </message>
    <message>
        <source>Would you delete the profile and configuration file?
If you click &apos;No&apos; only the profile from list will be removed.</source>
        <translation></translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation></translation>
    </message>
    <message>
        <source>Open language file</source>
        <translation></translation>
    </message>
    <message>
        <source>Language file (*.*)</source>
        <translation></translation>
    </message>
    <message>
        <source>Open DOSBox stabel binary</source>
        <translation></translation>
    </message>
    <message>
        <source>DOSBox binary (dosbox)</source>
        <translation></translation>
    </message>
    <message>
        <source>DOSBox Version: </source>
        <translation></translation>
    </message>
    <message>
        <source>Open DOSBox CVS binary</source>
        <translation></translation>
    </message>
    <message>
        <source>dosbox cmd output -&gt;</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Remove profile</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Create profile</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Quit</source>
        <translation></translation>
    </message>
    <message>
        <source>&lt;font color=darkblue&gt;&lt;u&gt;&lt;b&gt;Game Profile Menu&lt;/b&gt;&lt;/u&gt;&lt;/font&gt;</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>DBoxFE_Profile</name>
    <message>
        <source>Profilename</source>
        <translation></translation>
    </message>
    <message>
        <source>&amp;Abort</source>
        <translation></translation>
    </message>
    <message>
        <source>Ok</source>
        <translation></translation>
    </message>
    <message>
        <source>Profilename:</source>
        <translation>Profilename:</translation>
    </message>
</context>
</TS>
